title: DerekHouck.com
permalink: /:year/:month/:day/:title

collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

exclude: [vendor]
github: [metadata]

plugins:
  - jekyll-last-modified-at
  - jekyll-seo-tag
  - jekyll-responsive-image

# Images
cloudinary_url: https://res.cloudinary.com/dlwgq6st9/image/upload

# Last modified at plugin
last-modified-at:
    date-format: '%B %e, %Y'