title: DerekHouck.com
author: Derek Houck
description: The personal website of Derek Houck, an actor turned software engineer.
url: https://derekhouck.com
permalink: /:year/:month/:day/:title

collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

exclude: [vendor]
github: [metadata]

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-responsive-image

# Images
cloudinary_url: https://res.cloudinary.com/dlwgq6st9/image/upload